# Generated by Django 6.0.5 on 2026-05-31 17:51

import django.core.validators
import django.db.models.deletion
import property.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.FloatField(validators=[django.core.validators.MaxValueValidator(999999999.99)])),
                ('status', models.CharField(choices=[('S', 'Sale'), ('R', 'Rent'), ('L', 'Lease'), ('A', 'Auction')], max_length=1)),
                ('type', models.CharField(choices=[('R', 'Residential'), ('C', 'Commercial'), ('I', 'Industrial'), ('A', 'Agricultural')], max_length=1)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(default='US', max_length=50)),
                ('zip', models.CharField(blank=True, max_length=20, null=True)),
                ('features', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=500, primary_key=True, serialize=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property/images')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='property.property')),
            ],
        ),
        migrations.CreateModel(
            name='VisitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_date', models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=property.models.VisitRequest.get_today)])),
                ('message', models.CharField(max_length=1000, null=True)),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('CO', 'Confirmed'), ('CM', 'Completed'), ('DE', 'Declined'), ('CN', 'Cancelled')], default='P', max_length=2)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_visit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
