# Generated by Django 6.0.5 on 2026-06-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_propertyimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='rank',
            field=models.CharField(choices=[('P', 'Primary'), ('S', 'Secondary'), ('N', 'None')], default='N', max_length=1),
        ),
    ]
